### ISSUE TITLE
App does not detect when unable to connect to servers

### ISSUE THREAD

**Issue by shadowninja108** [vgmoose/wiiu-hbas#22]
I was having DNS problems (unrelated) and attempted to open the AppStore. The app would stay at "Downloading app catalog" for a while then load the App Store. The apps I did have were listed as Local but nothing else was listed. When I opened a category, it was empty. If I hit the random button, it crashed.

**Comment by vgmoose** [comment]
ah yeah, this would be nice. Probably a popup notification explaining the server couldn't be reached + fixing the random button crash
