### ISSUE TITLE
Hang if a homebrew has no folder

### ISSUE THREAD

**Issue by shadowninja108** [vgmoose/wiiu-hbas#23]
Title might not make sense but I will try to make sense of it. I had a homebrew (HID config helper or something) that the elf and meta was simply in sd:/wiiu/apps. Not in any folder. This would cause a hang at the "One moment" screen. Haven't had the time to test this issue further as I only noticed it once, but I do believe it is the cause. I'll test it soon, but either way there is a bug somewhere.

**Comment by shadowninja108** [comment]
I had a look in the closed issues and noticed this is not the first time that this has been reported. I'm going to double check I have the latest version and try to replicate this ASAP.

**Comment by shadowninja108** [comment]
I've tried on the latest release and it does occur. I have tried compiling the latest build but haven't been able to get it to work.

**Comment by vgmoose** [comment]
Oh, looks like #14 is back then 😞 I can confirm the issue as well. Fix is probably similar.
