### ISSUE TITLE
Meta.xml Attributes

### ISSUE THREAD

**Issue by vgmoose** [vgmoose/wiiu-hbas#3]
There should be further xml attributes:

To help with filtering games+apps (#1):
<category>game</category>
or 
<category>tool</category>

There should also be permission attributes for #4

**Comment by pwsincd** [comment]
category  added to all current xmls
current xml structure is : name/coder/version/url/release date/short description/long description/category

from a web stand point the only unused item is release date

is this needed..???

**Comment by CreeperMario** [comment]
> from a web stand point the only unused item is release date

It could be used to organise homebrew by release date, but this is more of an aesthetic feature and isn't really needed to make the program work.

**Comment by vgmoose** [comment]
Closing this as Permissions (#4) covers the remaining XML attributes that are needed.
